#
# Build stage
#
FROM node:16-alpine as builder

ARG NPM_TOKEN
ENV NPM_TOKEN $NPM_TOKEN

RUN mkdir -p /home/node/app/node_modules && mkdir -p /home/node/app/build && chown -R node:node /home/node/app

WORKDIR /home/node/app

USER node

COPY package*.json ./

RUN if [ "$NPM_BUILD" = "true" ]; then npm install --no-save --production=false && npm run build && rm -rf node_modules; fi
RUN npm install --no-save --production=true && rm ~/.npmrc

COPY --chown=node:node . .

#
# Running stage
#
FROM node:16-alpine

WORKDIR /home/node/app
USER node

# prevent leaking secrets by using multi-stage build copy
COPY --from=builder /home/node/app/node_modules ./node_modules
COPY --from=builder /home/node/app/build ./build

EXPOSE 8080
ENV NODE_ENV=production
CMD [ "npm", "run", "start:prod" ]
